name: cs138_hw3_env
channels:
  - conda-forge
  - defaults
dependencies:
  - autograd
  - cairosvg
  - git
  - ipykernel
  - jupyter_client
  - jupytext
  - matplotlib==3.8.4
  - numpy=1.23
  - pandas==2.2.2
  - plotly
  - pynvim
  - pyperclip
  - python-kaleido
  - python=3.10
  - scikit-learn==1.4.2
  - scikit-surprise
  - scipy==1.13.0
  - seaborn==0.13.2
  - xgboost
  - gymnasium-box2d
  - swig
