name: cs138_hw3_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cairosvg
  - ipykernel
  - jupyter_client
  - jupytext
  - plotly
  - pynvim
  - pyperclip
  - python-kaleido
  - python=3.10
  - gymnasium-box2d
  - swig
